spring.application.name=Logging

logging.level.root=INFO
logging.level.com.example=DEBUG


#Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true
management.endpoint.enabled-by-default=false
management.endpoint.web.exposure.exclude=beans
